# Links on sidebar
menu:
  Lastest: /
  Posts: /archives/
  Works: /about/
  Categories: /categories/
  Tags: /tags/
  Novice F2E: /categories/前端新手村/
  # Commonweal: /404.html

# Pictures shown on the sidebar
# Use the absolute URL after generating
# avatar: https://avatars1.githubusercontent.com/u/1825852?v=3&s=460
avatar: /assets/head.svg
sidebar_background: #/assets/header.png

# rss: /atom.xml

# Content
excerpt_link: 看看這篇好了...

# Will be shown on the bottom.
## To add new icon, just copy .svg to source/assets/ and add entries below.
media:
  github-alt: https://github.com/dwatow
  facebook-f: https://www.facebook.com/dwatow
  linkedin-in: https://www.linkedin.com/in/chris-wang-604469107

source_han_font: true

gitalk:
  enable: post
  on: true
  owner: dwatow
  repo: dwatow.github.io
  admin: ['dwatow']
  labels: ['Gitalk']
  clientID: '415f51e137fa564654af'
  clientSecret: 'e2912ef418f3ce73af7d465a5ab93bbf374a2228'

# Miscellaneous
favicon: /favicon.png
